//! Commit–reveal: direction secret, amount public.

use crate::amount::Amount;
use crate::crypto::hash_tagged;
use crate::encode::{TAG_COMMIT, TAG_REVEAL};
use crate::types::{Direction, Hash};

/// 32-byte opening salt. Generated by the host / user device.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Salt(pub [u8; 32]);

impl Salt {
    pub const fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    pub const fn from_byte(n: u8) -> Self {
        let mut bytes = [0u8; 32];
        bytes[0] = n;
        Self(bytes)
    }

    pub const fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }
}

/// Paid first-round commitment: public amount + hash of `(direction, amount, salt)`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct PaidCommitment {
    pub amount: Amount,
    pub hash: Hash,
}

/// Free first-round commitment (zero-balance users). Amount is implicitly zero.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct FreeCommitment {
    pub hash: Hash,
}

/// Second-round commitment: hash of `(original_commit, direction, salt)`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RevealCommit {
    pub hash: Hash,
}

/// Preimage published in the opening window.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Opening {
    pub direction: Direction,
    pub salt: Salt,
}

impl Opening {
    pub const fn new(direction: Direction, salt: Salt) -> Self {
        Self { direction, salt }
    }

    /// First-round hash binding `amount` (public) to this secret direction + salt.
    pub fn commit_hash(&self, amount: Amount) -> Hash {
        commit_hash(self.direction, amount, &self.salt)
    }

    /// Paid commitment record a host posts during the betting window.
    pub fn paid_commitment(&self, amount: Amount) -> PaidCommitment {
        PaidCommitment {
            amount,
            hash: self.commit_hash(amount),
        }
    }

    /// Free commitment record (amount hashed as zero).
    pub fn free_commitment(&self) -> FreeCommitment {
        FreeCommitment {
            hash: self.commit_hash(Amount::ZERO),
        }
    }

    /// Second-round hash, bound to the first-round digest.
    pub fn reveal_hash(&self, original: Hash) -> Hash {
        reveal_hash(original, self.direction, &self.salt)
    }

    pub fn reveal_commit(&self, original: Hash) -> RevealCommit {
        RevealCommit {
            hash: self.reveal_hash(original),
        }
    }
}

pub fn commit_hash(direction: Direction, amount: Amount, salt: &Salt) -> Hash {
    hash_tagged(TAG_COMMIT, |e| {
        e.u8(direction.wire());
        e.u64(amount.subunits());
        e.bytes32(salt.as_bytes());
    })
}

pub fn reveal_hash(original: Hash, direction: Direction, salt: &Salt) -> Hash {
    hash_tagged(TAG_REVEAL, |e| {
        e.bytes32(original.as_bytes());
        e.u8(direction.wire());
        e.bytes32(salt.as_bytes());
    })
}

pub fn verify_commit(expected: Hash, amount: Amount, opening: &Opening) -> bool {
    opening.commit_hash(amount) == expected
}

pub fn verify_reveal(expected: Hash, original: Hash, opening: &Opening) -> bool {
    opening.reveal_hash(original) == expected
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Opening {
        Opening::new(Direction::Yes, Salt::from_byte(3))
    }

    #[test]
    fn honest_opening_verifies() {
        let o = sample();
        let amount = Amount::TOKEN;
        let c = o.paid_commitment(amount);
        let r = o.reveal_commit(c.hash);
        assert!(verify_commit(c.hash, amount, &o));
        assert!(verify_reveal(r.hash, c.hash, &o));
    }

    #[test]
    fn wrong_salt_fails() {
        let o = sample();
        let amount = Amount::TOKEN;
        let c = o.paid_commitment(amount);
        let bad = Opening::new(Direction::Yes, Salt::from_byte(4));
        assert!(!verify_commit(c.hash, amount, &bad));
    }

    #[test]
    fn tampered_public_amount_fails() {
        let o = sample();
        let c = o.paid_commitment(Amount::TOKEN);
        assert!(!verify_commit(
            c.hash,
            Amount::from_subunits(Amount::TOKEN.subunits() + 1),
            &o
        ));
    }

    #[test]
    fn reveal_not_bound_to_other_commit_fails() {
        let o = sample();
        let c1 = o.paid_commitment(Amount::TOKEN);
        let other = Opening::new(Direction::No, Salt::from_byte(9)).paid_commitment(Amount::TOKEN);
        let r = o.reveal_commit(c1.hash);
        assert!(!verify_reveal(r.hash, other.hash, &o));
    }

    #[test]
    fn flipped_direction_fails() {
        let o = sample();
        let c = o.paid_commitment(Amount::TOKEN);
        let flipped = Opening::new(Direction::No, o.salt);
        assert!(!verify_commit(c.hash, Amount::TOKEN, &flipped));
    }

    #[test]
    fn free_commitment_hashes_zero_amount() {
        let o = sample();
        assert_eq!(o.free_commitment().hash, o.commit_hash(Amount::ZERO));
    }
}
